name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build (and unit testing)
        run: ./gradlew clean build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build, Push and Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 64971a84-77eb-482c-8214-cc0909a45b0d
          heroku_app_name: rsoi-22-lab1-ci-cd-peepoclown
          heroku_email: "mergeconflictsveteran@gmail.com"
          usedocker: true

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"